version: '3'

services:
  domain-tester:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GITHUB_DOMAINS_URL=${GITHUB_DOMAINS_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_DOMAIN_FILES=${GITHUB_DOMAIN_FILES}
      - GITHUB_REFRESH_INTERVAL=${GITHUB_REFRESH_INTERVAL:-1800}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    volumes:
      - ./screenshots:/app/screenshots
      - ./logs:/app/logs
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    ports:
      - "127.0.0.1:6380:6379"

volumes:
  redis-data: